
spring:
  datasource:
    url: jdbc:oracle:thin:@118.25.35.116:1521:helowin
    username: swhy
    password: password
    driver-class-name: oracle.jdbc.driver.OracleDriver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  redis:
    # 是否开启redis缓存  true开启   false关闭
    open: true
    database: 1
    host: localhost
    port: 6379
    # 密码（默认为空）
    password:
    # 连接超时时长（毫秒）
    timeout:  6000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1000
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 5
    expire: 30000

