feign:
  url:
    servicename: localhost:9002

spring:
  datasource:
    url: jdbc:oracle:thin:@118.25.35.116:1521:helowin
    username: swhy
    password: password
    driver-class-name: oracle.jdbc.driver.OracleDriver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true

